server:
  port: 8085

spring:
  application:
    name: user-center  #微服务名称

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.16.186:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
